feat: add connection with API categories in Products Page
intive/patronage22_lublin_js_frontend pull request #14
Opened 2022-04-19 19:13 UTC by kamilszalast

2022-04-20 07:49 UTC, dblach-intive requested changes

2022-04-20 07:49 UTC, dblach-intive commented on src/lib/categories.tsx
> +    "http://proxy-patronageapi.bsolutions.usermd.net/api/categories"
this http://proxy-patronageapi.bsolutions.usermd.net should be in variable somewhere in config

2022-04-20 07:49 UTC, dblach-intive commented on src/lib/categories.tsx
> +  const res = await axios.get(
use try catch block

2022-04-20 07:49 UTC, dblach-intive commented on src/lib/categories.tsx
> +  const res = await axios.get(
use try catch block

2022-04-20 07:49 UTC, dblach-intive commented on src/pages/products/index.tsx
> +    category: "Komputery",
category should be a number not string in database we have categoryId field so we will sort by ID

2022-04-20 07:49 UTC, dblach-intive commented on src/pages/products/index.tsx
> +      categories: categories.map((category: any) => ({
type any category

2022-04-20 07:49 UTC, dblach-intive commented on src/pages/products/index.tsx
> +        createdAt: category.createdAt,
we dont need createdAt

2022-04-20 07:49 UTC, dblach-intive commented on src/pages/products/index.tsx
> +        updatedAt: category.updatedAt,
we dont need updatedAt

2022-04-20 07:49 UTC, dblach-intive commented on src/types/models.ts
> +  createdAt: string;
optional

2022-04-20 07:49 UTC, dblach-intive commented on src/types/models.ts
> +  updatedAt: string;
optional

2022-04-20 13:51 UTC, kamilszalast commented on src/lib/categories.tsx
> +    "http://proxy-patronageapi.bsolutions.usermd.net/api/categories"
added in src/types/constants

2022-04-20 13:58 UTC, kamilszalast commented on src/lib/categories.tsx
> +  const res = await axios.get(
done

2022-04-20 14:08 UTC, kamilszalast commented on src/pages/products/index.tsx
> +        createdAt: category.createdAt,
done

2022-04-20 14:08 UTC, kamilszalast commented on src/types/models.ts
> +  createdAt: string;
done

2022-04-20 14:08 UTC, kamilszalast commented on src/types/models.ts
> +  updatedAt: string;
done

2022-04-21 10:09 UTC, dblach-intive requested changes

2022-04-21 10:09 UTC, dblach-intive commented on src/lib/categories.tsx
> +export async function loadCategories() {
getCategories will be better name for this function

2022-04-21 10:09 UTC, dblach-intive commented on src/components/ProductList/index.tsx
can we destructure props here? it will be cleaner, const {price,.....} = props;

2022-04-21 10:09 UTC, dblach-intive commented on src/components/ProductList/index.tsx
> +            return product.price <= props.price && props.category !== 0
after destructure {price} {category} etc

2022-04-21 10:09 UTC, dblach-intive commented on src/components/ProductList/index.tsx
> +            return product.price <= props.price && props.category !== 0
same here

2022-04-21 10:09 UTC, dblach-intive commented on src/lib/categories.tsx
> +    const res = await axios.get(`${CONSTANTS.URL}/api/categories`);
const {data: Category[]} = await....

2022-04-21 10:09 UTC, dblach-intive commented on src/lib/categories.tsx
> +    const res = await axios.get(
const {data: Category[]} = await....

2022-04-21 10:09 UTC, dblach-intive commented on src/pages/products/index.tsx
> +  id: 0,
id: null will be ok ?

2022-04-21 10:09 UTC, dblach-intive commented on src/lib/categories.tsx
> +    const data: Category = await res.data;
dont need to to await here - after destructurization this will be for remove

2022-04-21 10:09 UTC, dblach-intive commented on src/components/Categories/index.tsx
> -  const categories = [
destructure props here

2022-04-21 10:09 UTC, dblach-intive commented on src/components/Categories/index.tsx
> +        {props.categoriesList.map((category) => {
categoriesList?.map

2022-04-21 12:01 UTC, kamilszalast commented on src/pages/products/index.tsx
> +  id: 0,
didn't change it

2022-04-21 13:08 UTC, dblach-intive approved these changes

2022-04-21 13:19 UTC, merged